describe("Build01",() => {
    it("Add & Remove the product from the cart", async () => {
        await browser.maximizeWindow()
        await browser.url("https://demowebshop.tricentis.com/")
        await browser.$("//a[contains(text(),'Log in')]").click()
        await browser.$('#Email').setValue("zayen.demha001@gmail.com")
        await browser.$('#Password').setValue("Neyaz94@96")
        await browser.$("//input[@value='Log in']").click()
        await browser.$("//a[@title='Show details for $25 Virtual Gift Card']").scrollIntoView()
        await browser.pause(2000)
        await browser.$("//a[@title='Show details for $25 Virtual Gift Card']").moveTo()
        await browser.pause(2000)
        await browser.$("=Apparel & Shoes").click()
        await browser.$('#products-orderby').selectByVisibleText('Price: Low to High')
        await browser.$("[name='products-pagesize']").selectByIndex(0)
        await browser.$("[name='products-viewmode']").selectByIndex(1)
        await browser.$("=Blue Jeans").click()
        await browser.$("#add-to-cart-button-36").click()
        let url = await browser.getUrl()
        console.log(url);
        let text = await browser.$("//p[@class='content']").getText()
        console.log(text);
        let title = await browser.getTitle()
        console.log(title);
        await browser.$("//span[@class='close']").click()
        await browser.$("//div[@class='column my-account']/descendant::a[text()='Shopping cart']").scrollIntoView()
        await browser.pause(2000)
        await browser.$("//div[@class='header-links']/descendant::span[text()='Shopping cart']").scrollIntoView()
        await browser.$("//div[@class='header-links']/descendant::span[text()='Shopping cart']").click()
        await browser.pause(2000)
        await browser.$("[name='removefromcart']").click()
        await browser.$("[name='updatecart']").click()
        await browser.pause(3000)
        await browser.$("//a[@class='ico-logout']").click()
        await browser.navigateTo("https://www.facebook.com/")
        await browser.pause(1000)
    })
})